version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres-trixie
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: unless-stopped